### ISSUE TITLE
GeckoLib issues?

### ISSUE THREAD

**Issue by Ultimushadow** [Kitisplode/minecraftMod-golemFirstStone#5]
Hey there, I was having some problems when loading a world with this mod, essentially I would get to a certain point and freeze (usually around 90-98%). The modpack I was in had about 300 more mods than I was willing to try to rule out one by one so I went to go test the mod by itself, where it gave me an actual crash report, attached below. The crash report mentions GeckoLib, which I assume you are using for your animations, but the mod does not have it listed as a dependency (at least not v0.0.7 which I am using). When I installed GeckoLib, the mod loaded just fine. However, it continues to freeze my other pack so I have not narrowed down the cause yet. 

The other pack ends up repeating this multiple times: 
[02:38:55] [C2ME worker #2/WARN] (SaveUtil) Failed to load light for chunk [-10, -12], light will be recalculated
java.lang.ArrayIndexOutOfBoundsException: Index 26 out of bounds for length 26
	at ca.spottedleaf.starlight.common.util.SaveUtil.loadLightHookReal(SaveUtil.java:168) ~[starlight-1.1.2+fabric.dbc156f.jar:?]
	at ca.spottedleaf.starlight.common.util.SaveUtil.loadLightHook(SaveUtil.java:129) ~[starlight-1.1.2+fabric.dbc156f.jar:?]
	at net.minecraft.world.ChunkSerializer.handler$iig000$starlight$loadLightHook(ChunkSerializer.java:2602) ~[client-intermediary.jar:?]
	at net.minecraft.world.ChunkSerializer.deserialize(ChunkSerializer.java:220) ~[client-intermediary.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.md7fb494$c2me-threading-chunkio$lambda$loadChunk$3$2b(ThreadedAnvilChunkStorage.java:15626) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	
I can tell that both Concurrent Chunk Management Engine and Starlight are in the trace here but I loaded them up on the test pack and they didn't cause issues with Dandori so I think something else is causing this, I'm looking into it now but I wanted to let you know about the dependency first. Once I get some more solid information I'll update with full info on mod versions and such

Crash Report: [crash-2023-08-31_02.28.33-client.txt](https://github.com/Kitisplode/minecraftMod-golemFirstStone/files/12483741/crash-2023-08-31_02.28.33-client.txt)

**Comment by Ultimushadow** [comment]
So far it looks like it's specific to a superflat world made before installing Dandori, because I loaded up a previous world save from a normal world and it lagged but worked fine, then I created a new superflat and that worked fine too.... I don't know what is actually freezing it but I will try to find out later. Also, it might be worth not letting superflat generate below the mining fatigue line, it doesn't make much sense to make basically the whole world apply mining fatigue

**Comment by Kitisplode** [comment]
Yeah the dimension height extension went in a way i didn't expect it to, i removed those changes recently, so version 0.0.7 (no dandori caves version on curseforge), 0.0.8, and later versions will not have this particular world generation issue i think
i hope

**Comment by Ultimushadow** [comment]
When it comes to world generation I think hoping is the only viable strategy 😂 
I'll switch to the new version when I get the chance, thanks for looking into it!

**Comment by Ultimushadow** [comment]
Going to close this out since the removal of the under-bedrock generation in the recent update has fixed the issue. Thank you for getting that done so fast!
